models:
  InceptionV3:
    max_width: 299
    max_height: 299
  InceptionResNetV2:
    max_width: 299
    max_height: 299
  ResNet50:
    max_width: 299
    max_height: 299
  NASNetMobile:
    max_width: 224
    max_height: 224
  default:
    max_width: 224
    max_height: 224

optimizers:
  - RMSprop
  - Adam
  - AMSGrad
  - SGD

batch_sizes:
  - 8
  - 16
  - 32
  - 64
  - 128

epoch_propositions:
  - 1
  - 3
  - 10
  - 20
  - 50
  - 100
  - 250
  - 500
  - 1000

pas_propositions:
  - 0.01
  - 0.001
  - 0.0001
  - 0.00001

nb_layers_to_freeze:
  - 10
  - 50
  - 100
  - 150
  - 249